spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/English?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: skywalker&me999
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
      dialect: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  resources:
    static-locations: classpath:/resources/,classpath:/static/,classpath:/templates/
  mvc:
    static-path-pattern: /**
  redis:
    database: 0
    host: localhost
    port: 6379
    password: skywalker&me999
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
server:
  port: 8088